language: python
sudo: required
python:
    - "2.6"
    - "2.7"
addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
install:
    - bash bin/travis-build.bash
    - pip install coveralls
script: sh bin/travis-run.sh
after_success:
    - coveralls
